# Generated by Django 5.0 on 2023-12-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=100)),
                ('title2', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sample')),
            ],
        ),
    ]
