# Generated by Django 5.0 on 2023-12-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='title2',
            new_name='category',
        ),
    ]
