# Generated by Django 5.0 on 2023-12-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_rename_title2_sample_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
